RecipeBook/Models/Recipe.cs
using System.Collections.Generic;

namespace RecipeBook.Models
{
    public class Recipe
    {
        public Recipe()
        {
            this.Ingredients = new HashSet<RecipeIngredient>();
            this.Categories = new HashSet<RecipeCategory>();
            this.Instructions = new HashSet<Instruction>();
        }

        public int RecipeId {get;set;}
        public string Name {get;set;}
        
        public int Rating {get;set;}

        public ICollection<RecipeIngredient> Ingredients {get;set;}
        public ICollection<RecipeCategory> Categories {get;set;}
        public ICollection<Instruction> Instructions {get;set;}

    }
}

RecipeBook/ViewModels/RecipeView.cs
using System.ComponentModel.DataAnnotations;
using RecipeBook.Models;
using System.Collections.Generic;

namespace RecipeBook.ViewModels
{
    public class RecipeView
    {
        public Recipe Recipe {get;set;}
        public List<Category> Categories {get;set;}
        public List<Ingredient> Ingredients {get;set;}
    }
}

RecipeBook/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeBook.Models;
using RecipeBook.Data;

namespace RecipeBook.Controllers {
    public class IngredientController : Controller {
        private readonly ApplicationDbContext _db;

        public IngredientController(ApplicationDbContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            var model = _db.Ingredients.ToList();
            return View(model);
        }
        public ActionResult Create () {
            ViewBag.RecipeId = new SelectList (_db.Recipes, "RecipeId", "Name");
            return View ();

        }

        [HttpPost]
        public ActionResult Create (Ingredient ingredient) {
            _db.Ingredients.Add (ingredient);
            _db.SaveChanges ();
            return RedirectToAction ("Index");
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = _db.Ingredients.FirstOrDefault(i => i.IngredientId == id);
            return View(model);
        }

    }
}

RecipeBook/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeBook.Data;
using RecipeBook.Models;
using RecipeBook.ViewModels;

namespace RecipeBook.Controllers {

    public class RecipeController : Controller {
        private readonly ApplicationDbContext _db;

        public RecipeController (ApplicationDbContext db) {
            _db = db;
        }

        public ActionResult Index () {
            var model = _db.Recipes.ToList ();
            return View (model);
        }

        public ActionResult Create () {
            return View ();
        }

        [HttpPost]
        public ActionResult Create (Recipe recipe) {
            _db.Recipes.Add (recipe);
            _db.SaveChanges ();
            return RedirectToAction ("AddIngredient", "Recipe", new {id = recipe.RecipeId });
        }

        [HttpGet]
        public ActionResult AddIngredient (int id)
        {
            ViewBag.IngredientDropDown = new SelectList (_db.Ingredients, "IngredientId", "Name");
            ViewBag.RecipeId = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddIngredient(RecipeIngredient ingredient)
        {
            _db.RecipeIngredients.Add(ingredient);
            _db.SaveChanges();
            return RedirectToAction("AddCategory", "Recipe", new{id= ingredient.RecipeId});

        }

        [HttpGet]
           public ActionResult AddCategory (int id)
        {
            ViewBag.CategoryDropDown = new SelectList (_db.Categories, "CategoryId", "Name");
            ViewBag.RecipeId = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(RecipeCategory category)
        {
            _db.RecipeCategories.Add(category);
            _db.SaveChanges();
            return RedirectToAction("Index", "Recipe");

        }

        [HttpGet]
           public ActionResult Details (int id)
        {
            // var thisRecipe = (from r in ApplicationDbContext.Recipes
            //     join i in ApplicationDbContext.RecipeIngredients on r.RecipeId equals i.RecipeId
            //     join c in ApplicationDbContext.RecipeCategories on r.RecipeId equals c.RecipeId
            //     where r.RecipeId == id
            //     select new {
            //         RecipeID = id;
            //     })
            //recpie -> list catergory -> list ingredients

            var thisRecipe = _db.Recipes
            .FirstOrDefault(r => r.RecipeId == id);

            var theseCategories = _db.RecipeCategories
            .Where(rc => rc.RecipeId == id)
            .Select(rc => rc.CategoryId).ToList();

            var includedCategories = _db.Categories
            .Where(c => theseCategories.Contains(c.CategoryId)).ToList();

            var theseIngredients = _db.RecipeIngredients
            .Where(ri => ri.RecipeId == id)
            .Select(ri => ri.IngredientId).ToList();

            var includedIngredients = _db.Ingredients
            .Where(i => theseIngredients.Contains(i.IngredientId)).ToList();

            RecipeView model = new RecipeView(){Recipe=thisRecipe, Categories=includedCategories, Ingredients=includedIngredients};
            return View(model);
        }



    }

}

RecipeBook/Views/Recipe/AddCategory.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBook.Models.RecipeCategory
@{var dropdown = ViewBag.CategoryDropDown as SelectList;}

@using (Html.BeginForm())
{
    <h4> Ingredients: @Html.DropDownListFor(model => model.CategoryId, dropdown, "--Select Category--")</h4>
    <input type="hidden" value=@($"{ViewBag.RecipeId}") name="RecipeId">



    <input type="submit" value="Add Category" class="btn btn-default">
    
}

RecipeBook/Views/Recipe/AddIngredient.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBook.Models.RecipeIngredient
@{var dropdown = ViewBag.IngredientDropDown as SelectList;}

@using (Html.BeginForm())
{
    <h4> Ingredients: @Html.DropDownListFor(model => model.IngredientId, dropdown, "--SelectIngredient")</h4>

    <input type="hidden" value=@($"{ViewBag.RecipeId}") name="RecipeId">
    //binds the value of ViewBag RecipeId value to the RecipieIngredient id in the model




    <input type="submit" value="Add ingredients" class="btn btn-default">
    
}

RecipeBook/Views/Recipe/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBook.Models.Recipe

@using (Html.BeginForm())
{
    <h4> Recipe: @Html.TextBoxFor(model => model.Name)</h4>
    <h4> Ingredients: @Html.TextBoxFor(model => model.Name)</h4>

    <input type="submit" value="Save new recipe" class="btn btn-default">
}

RecipeBook/Views/Recipe/Details.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBook.ViewModels.RecipeView

<h2>Item Details</h2>
<hr>

<h3>Ingredient: @Html.DisplayFor(model => model.Recipe.Name)</h3>

@if(@Model.Ingredients.Count == 0)
{
  <p>This item does not belong to any recipes</p>
}
else
{
  <h4>Ingredients:</h4>
  <ul>
  @foreach(Ingredient ingredient in Model.Ingredients)
  {
    <li>@ingredient.Name</li>
     @using (Html.BeginForm("DeleteRecipe", "Ingredient"))
    {
      @Html.Hidden("joinId", @ingredient.IngredientId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
  <ul>
      @foreach(Category c in Model.Categories)
    {
    <li>@c.Name</li>
     @using (Html.BeginForm("DeleteRecipe", "Ingredient"))
    {
      @Html.Hidden("joinId", @c.CategoryId)
      <input type="submit" value="Delete"/>
    }
    }
  </ul>
}

RecipeBook/Views/Recipe/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBook.Models;
@model List<Recipe>;

<h2>Recipes</h2>


@if (Model.Any())
{
  <ul>
    @foreach (Recipe recipe in Model)
    {
      <li>@Html.ActionLink($"{recipe.Name} |{recipe.Rating}" , "Details", new { id = recipe.RecipeId })</li>
    }
  </ul>
  
}
else
{
  <h3>No items have been added yet!</h3>
}

<p>@Html.ActionLink("Add new recipe", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>